# Generated by Django 2.1.15 on 2022-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('n_control', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('curp', models.CharField(max_length=18)),
                ('t_sangre', models.CharField(max_length=3)),
                ('alergias', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
                ('foto', models.BinaryField(max_length=10000)),
            ],
        ),
    ]
